### ISSUE TITLE
Probably something wrong in the configuration

### ISSUE THREAD

**Issue by CedricLor** [locomotivecms/heroku-instant-deploy#6]
Hi,

Thanks for this instant deploy.

However, there is probably something wrong in the configuration (but I can't figure out what).

When pushing any website developed with Wagon (even the most simplistic one automatically generated by Wagon), you receive a "connection reset by peer".

The site seems however to have been at least partially pushed as it appears as having been created in the Engine's UI.

Then when trying to navigate to the site (preview or live preview), you end up on the "usual heroku something went wrong page". I haven't had time to check the logs but can do later and keep you posted.

Many thanks

Cédric

**Comment by did** [comment]
it also needs a new version coal: https://github.com/locomotivecms/coal/commit/7d7b0f9510c84ac412b12e0f74d947b02f7ed6c6

**Comment by did** [comment]
Work-around: in the config/deploy.yml file, remove the :443 at the end of the host and add `ssl: true` as an option.
We won't have to do that in the next release of Wagon (2.0.0.rc6).
